---
name: "tiller"
version: "0.6.0"
usage: "Please see https://github.com/rimusz/helm-tiller for usage"
description: "Start a Tiller server locally"
command: "$HELM_PLUGIN_DIR/scripts/tiller.sh"
useTunnel: false
